name: Write and Push File

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  write-and-push:
    name: Write and Push File
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Write File
      run: echo "This is a new file created by the GitHub Actions workflow" > newfile.txt
      
    - name: Commit and Push Changes
      run: |
        git config --local user.email "twincacca@gmail.com"
        git config --local user.name "twincacca"
        git add newfile.txt
        git commit -m "Add new file via GitHub Actions"
        git push
        
